sns/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    post "/like", to: "likes#like_toggle"
    post "/dislike", to: "dislike#dislike_toggle"
    resources :ments, only: [:create, :destroy]
  end
  resources :follows, only: [:create, :destroy]
  
  get 'mypage/index'
  get 'tagpage/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sns/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sns/app/models/dislike.rb
class Dislike < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

sns/app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

sns/app/models/htg.rb
class Htg < ApplicationRecord
    has_many :post
end

sns/app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

sns/app/models/ment.rb
class Ment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

sns/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :dislikes, source: :user
    has_many :dislikes
    has_many :disliked_users, through: :dislikes, source: :user
    has_many :ments
    has_many :htgs
    mount_uploader :image, PostImageUploader
    
    after_create do
        post = Post.find_by(id: self.id)
        hashtags = self.content.scan(/[#＃][a-z|A-Z|가-힣|ㄱ-ㅎ|ㅏ-ㅣ|0-9|\w]+/)
        hashtags.uniq.map do |hashtag|
            Htg.find_or_create_by(name: hashtag.downcase.delete('#'), post_id: self.id)
        end
    end
end

sns/app/models/posthtg.rb
class Posthtg < ApplicationRecord
    belongs_to :htg
    belongs_to :post
end

sns/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :dislikes, source: :post
  has_many :dislikes
  has_many :disliked_posts, through: :dislikes, source: :post
  has_many :ments
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower
  has_many :following_relation, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relation, source: :followed
  mount_uploader :avatar, AvatarUploader
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
  
  def is_dislike?(post)
    Dislike.find_by(user_id: self.id, post_id: post.id).present?
  end
end

sns/app/controllers/dislike_controller.rb
class DislikeController < ApplicationController
    before_action :authenticate_user!
    
    def dislike_toggle
        dislike = Dislike.find_by(user_id: current_user.id, post_id: params[:post_id])
        
        if dislike.nil?
            Dislike.create(user_id: current_user.id, post_id: params[:post_id])
        else
            dislike.destroy
        end
        
        redirect_to root_path
    end
end

sns/app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    
    def like_toggle
        like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
        
        if like.nil?
            Like.create(user_id: current_user.id, post_id: params[:post_id])
        else
            like.destroy
        end
        
        redirect_to root_path
    end
end

sns/app/controllers/ments_controller.rb
class MentsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_ownership!, only: [:destroy]
    
    def create
        new_comment = Ment.new(content: params[:content], post_id: params[:post_id], user_id: current_user.id)
        new_comment.save
        redirect_to root_path
    end
    
    def destroy
        @comment.destroy
        redirect_to root_path
    end
    
    private
        def check_ownership!
            @comment = Ment.find_by(id: params[:id])
            redirect_to root_path if @comment.user.id != current_user.id
        end
end

sns/app/controllers/mypage_controller.rb
class MypageController < ApplicationController
    before_action :authenticate_user!
    before_action :check_ownership, only: [:edit, :update, :destroy]
  
  def index
    @posts = current_user.posts.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end
end

sns/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ownership, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end
  
  def new
  end
  
  def create
    new_post = Post.new(user_id: current_user.id, content: params[:content], image: params[:image])
    if new_post.save
      redirect_to root_path
    else
      redirect_to new_post_path
    end
  end
  
  def edit
  end
  
  def update
    @post.content = params[:content]
    
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  private
  
  def check_ownership
     @post = Post.find_by(id: params[:id])
    redirect_to root_path if @post.user_id != current_user.id
  end
end

sns/app/helpers/application_helper.rb
module ApplicationHelper
end

sns/app/helpers/comments_helper.rb
module CommentsHelper
end

sns/app/helpers/dislike_helper.rb
module DislikeHelper
end

sns/app/helpers/follows_helper.rb
module FollowsHelper
end

sns/app/helpers/likes_helper.rb
module LikesHelper
end

sns/app/helpers/ments_helper.rb
module MentsHelper
end

sns/app/helpers/mypage_helper.rb
module MypageHelper
end

sns/app/helpers/posts_helper.rb
module PostsHelper
end

sns/app/helpers/tagpage_helper.rb
module TagpageHelper
end

sns/app/views/posts/_post.html.erb
<div class="card post">
                    <div class="card-content">
                        <% if post.user.avatar %>
                            <img class="circle thumbnail" src="<%= post.user.avatar.thumb.url %>">
                        <% end %>
                        <span class="card-title"><%= post.user.name %></span>
                        <span><%= post.created_at %></span>
                   
                        <% if user_signed_in? && current_user != post.user %>
                            <% if current_user.followings.include?(post.user) %>
                                <%= form_tag follow_path(post.user.id), method: :delete, class: "right" do %>
                                    <button class="btn blue darken-4">팔로우 취소</button>
                                <% end %>
                            <% else %>
                                <%= form_tag follows_path, method: :post, class: "right" do %>
                                    <input type="hidden" name="followed_id" value= "<%= post.user.id %>" >
                                    <button class="btn blue darken-4">팔로우</button>
                                <% end %>
                            <% end %>
                        <% end %>
                    
                        
                        <div class="card-image">
                            <br /><br />
                            <% if post.image.url %>
                                <img src="<%= post.image.url %>">
                            <% end %>
                        </div>
                        <p class="pre-line"><br /><%= post.content %></p>
                    </div>
                        
                    <div class="card-action">
                        <%= post.likes.size %> 명이 좋아합니다. &emsp;
                        <% if current_user.is_like?(post) %>
                            <%= link_to "좋아요 취소", post_like_path(post), method: "post", class: "pink-text text-accent-3" %>
                        <% else %>
                            <%= link_to "좋아요", post_like_path(post), method: "post", class: "pink-text text-accent-3" %>
                        <% end %>
                        <br />
                        <%= post.dislikes.size %> 명이 싫어합니다. &emsp;
                        <% if current_user.is_dislike?(post) %>
                            <%= link_to "싫어요 취소", post_dislike_path(post), method: "post", class: "pink-text text-accent-3" %>
                        <% else %>
                            <%= link_to "싫어요", post_dislike_path(post), method: "post", class: "pink-text text-accent-3" %>
                        <% end %>
                        <% if current_user.id == post.user_id %>
                            <%= link_to "삭제", post_path(post), method: "delete", class: "right pink-text text-accent-3" %>
                            <%= link_to "수정", edit_post_path(post), class: "right pink-text text-accent-3" %>
                        <% end %>
                        
                        <%= form_tag post_ments_path(post) do %>
                            <div class="input-field">
                                <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "댓글을 작성해주세요.", required: true %>
                            </div>
                          
                            <div class="input-field">
                                <%= button_tag "댓글 쓰기", class: "btn blue darken-4" %>
                            </div>
                        <% end %>
                        <% if post.ments.present? %>
                            <ul class="collection">
                                <% post.ments.each do |ment| %>
                                    <li class="collection-item">
                                        <span class="title"><%= ment.user.name %></span>
                                        <span class="right"><%= ment.created_at %></span>
                                        <p class="pre-line"><%= ment.content %></p>
                                        <% if ment.user.id == current_user.id %>
                                            <div><%= link_to "댓글 삭제", post_ment_path(post, ment), method: "delete", class: "pink-text text-accent-3" %></div>
                                        <% end %>
                                    </li>
                                <% end %>
                            </ul>
                        <% end %>
                    </div>
                </div>

sns/app/views/posts/edit.html.erb
<div class="container">
    <div class="row">
        <div class="card col s12">
            <div class="card-content">
                <div class="card-title">게시물 수정</div>
                  <%= form_tag post_path(@post), method: "patch" do %>
                      <input type="hidden" name="id" value="<%= @post.id %>">
                      <div class="input-field">
                          <%= text_area_tag :content, @post.content, class: "materialize-textarea", placeholder: "문구 입력" %>
                      </div>
                  
                      <div class="input-field">
                          <%= button_tag "수정하기", class: "btn blue darken-4" %>
                      </div>
                   <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

sns/app/views/posts/index.html.erb
<br />
<div style="height: 35px; width: 400px; border: 4px solid #1b5ac2; background: #ffffff; margin: auto;">
    <form action="/tagpage/index" method="get">
        &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="search" placeholder=" # 검색어 입력" style="font-size: 16px; width: 300px; height: 30px; border: 0px; outline: none;">
        <button type="submit" style="widtth: 50px; height: 30px; border: 0px; background: #1b5ac2; color: #ffffff; float: right;">검색</button>
    </form>
</div>

<br />
<div class="container">
    <div class="row">
        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img src="<%= current_user.avatar.url %>" />
                </div>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>올린 게시물 수 : <%= @posts_count %></p>
                    <p>팔로워 : <%= current_user.followers.length %></p>
                    <p>팔로잉 : <%= current_user.followings.length %></p>
                    <br />
                    <%= link_to new_post_path do %>
                        <button class="btn blue darken-4">글쓰기</button>
                    <% end %>
                    &nbsp;&nbsp;&nbsp;&nbsp;<a href="/mypage/index"><button class="btn blue darken-4">마이페이지</button></a>
                    
                </div>
            </div>
        </div>
        <div class="col s12 m8">
            <% @posts.each do |post| %>
                <%= render partial: "post", object: post %>
            <% end %>
        </div>
    </div>
</div>

sns/app/views/posts/new.html.erb
<div class="container">
    <div class="row">
        <div class="card col s12">
            <div class="card-content">
                <div class="card-title">게시물 작성</div>
                  <%= form_tag posts_path, multipart: true do %>
                      <div class="input-field">
                          <%= file_field_tag :image %>
                      </div>
                      <div class="input-field">
                          <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "문구 입력" %>
                      </div>
                  
                      <div class="input-field">
                          <%= button_tag "작성하기", class: "btn blue darken-4" %>
                      </div>
                   <% end %>
                </div>
            </div>
        </div>
    </div>
</div>